version: "3.3"
services:
  app:
    image: komik
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/komik
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      PORT: 3000
      LANG: en_US.UTF-8
      RACK_ENV: production
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: enabled
      RAILS_SERVE_STATIC_FILES: enabled
      DATABASE_URL: 'postgres://postgres:root@db:5432/komik_production'

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: komik_production
